version: "3"

services:
  postgres:
    build:
      context: "."
      dockerfile: "./dockerfiles/db/Dockerfile"
    ports:
      - "${DB_PORT}"
    volumes:
      - ./.db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST=${DB_HOST}

  service:
    build:
      context: "."
      dockerfile: "./dockerfiles/server/Dockerfile"
    ports:
      - "${PORT}:8080"
    depends_on:
      - postgres
    command: ./wait-for ${DB_HOST}:${DB_PORT} -- ./run
