version: "3"

services:
  service:
    build:
      context: "."
      dockerfile: "./dockerfiles/server/Dockerfile"
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"
    depends_on:
      - postgres
    command: ./wait-for postgres:${PG_PORT} -- ./run
