version: "3"

services:
  postgres:
    build:
      context: "."
      dockerfile: "./dockerfiles/db/Dockerfile"
    ports:
      - "${PG_PORT}"
    volumes:
      - ./src/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./.db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_NAME}
      - POSTGRES_HOST=${PG_HOST}

  service:
    build:
      context: "."
      dockerfile: "./dockerfiles/server/Dockerfile"
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"
    depends_on:
      - postgres
    command: ./wait-for postgres:${PG_PORT} -- ./run

  fake_agent:
    build:
      context: "."
      dockerfile: "./dockerfiles/fake_server/Dockerfile"
    ports:
      - "${AGENT_PORT}"
